### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by alfandango** [sacrish/Object-Sequence#1]
This is a great addon!  Just what I've been looking for, but have a suggestion.

Is it possible to include a button, (above 'Render Sequence' perhaps) to select material for all of the objects in target container?

**Comment by sacrish** [comment]
@alfandango Sorry if I didn't understand correctly. Do you mean you want to assign the same material to all objects in a collection?

If so, vanilla blender can do that. You can first select all the objects, assign a material, and use Ctrl+L -> Link Materials.

**Comment by alfandango** [comment]
@sacrish Yes, when I export the sequence it's useful to have all objects the same material and a button in the panel would be a great shortcut / reminder that allows you to pick from your current materials in the project.

Something like https://imgur.com/RDylY5r

**Comment by sacrish** [comment]
I see. Currently I'd like to keep this addon focusing on its major purpose, and personally I think material management seems a little "off-topic". So I'll put this feature request on hold for the time being.

However, you may want to try an addon which already comes with Blender called "Material Utilities". With that enabled, you can quickly assign or replace materials with the right-click menu. I hope it's helpful to you.

![Screenshot 2021-06-18 145720](https://user-images.githubusercontent.com/8361680/122519855-82295600-d045-11eb-971e-9ad332a4ac4d.png)
