### ISSUE TITLE
Crashes in Blender 3.0.1, if clearing the Sequence

### ISSUE THREAD

**Issue by JF-Siegmund** [sacrish/Object-Sequence#2]
Hello, great Plugin! Love it!

But crashes in Blender 3.0.1, if clearing the Sequence.

Problem fixed, if you use the obj.name from a list, to iterate over the collection.

> Object.hide_viewport, Object.hide_select and Object.hide_render: Setting any of those booleans will trigger a rebuild of Collection caches, hence breaking any current iteration over Collection.all_objects.

I changed the way it handles the objects from Collection.

```
# clear object sequence
def show_all(collection):
    scene = bpy.context.scene
    my_objects = []
    if not collection.all_objects:
        return
    for obj in collection.all_objects:
        my_objects.append(obj.name)
    for obj_name in my_objects:
        try:
            if obj is not None:
                obj = bpy.data.objects.get(obj_name)
                obj.animation_data_clear()
                obj.hide_render = False
                obj.hide_viewport = False
        except: 
            print("Can't find object to clear")
    scene.timeline_markers.clear()
```

**Comment by sacrish** [comment]
Thanks for the feedback and code! I haven't tested it with Blender 3.0+ yet. I'll take a look when I'm free.

**Comment by sacrish** [comment]
Tested your method and it's working now. Thank you very much again!
